/**
 * Testimonial sets for the site (Flow, Clarity, Protocol).
 * Data comes from app/lib/testimonialsFromLoox.ts (generated by npm run build:reviews).
 * See docs/REVIEWS_WORKFLOW.md for updating reviews from a new CSV.
 */
import type { LooxTestimonial, ProductType } from "@/app/lib/testimonialsFromLoox";
import {
  siteTestimonialsClarity,
  siteTestimonialsFlow,
  siteTestimonialsProtocol,
} from "@/app/lib/testimonialsFromLoox";
import type { Testimonial } from "@/app/components/testimonials/types";

const PRODUCT_LABELS: Record<ProductType, string> = {
  flow: "CONKA Flow",
  clarity: "CONKA Clear",
  protocol: "Protocol",
};

function toTestimonial(row: LooxTestimonial): Testimonial {
  return {
    name: row.name,
    country: "",
    rating: row.rating,
    date: row.date,
    headline: row.headline,
    body: row.body,
    photo: row.photo,
    productType: row.productType,
    productLabel: PRODUCT_LABELS[row.productType],
  };
}

export function getSiteTestimonialsFlow(): Testimonial[] {
  return siteTestimonialsFlow.map(toTestimonial);
}

export function getSiteTestimonialsClarity(): Testimonial[] {
  return siteTestimonialsClarity.map(toTestimonial);
}

export function getSiteTestimonialsProtocol(): Testimonial[] {
  return siteTestimonialsProtocol.map(toTestimonial);
}

/** Shuffle array (Fisher–Yates). Use for client-side variety e.g. Home/Barry's. */
export function shuffleTestimonials<T>(array: T[]): T[] {
  const out = [...array];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}
