export { default as ScienceHero } from "./ScienceHero";
export { default as ScienceQuote } from "./ScienceQuote";
export { default as ScienceAdaptogens } from "./ScienceAdaptogens";
export { default as SciencePillars } from "./SciencePillars";
export { default as PillarCard } from "./PillarCard";
export { default as SynergyChart } from "./SynergyChart";
export { default as ScienceDifferent } from "./ScienceDifferent";
export { default as EvidenceSummary } from "./EvidenceSummary";
export { default as SciencePageContent } from "./SciencePageContent";
